BEGIN TRANSACTION;

CREATE TABLE USERS (
    id UUID PRIMARY KEY,
    email VARCHAR UNIQUE,
    phone_number VARCHAR UNIQUE,
    name VARCHAR,
    image_url VARCHAR,
    password VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FRIENDS (
    id SERIAL PRIMARY KEY,
    a UUID REFERENCES USERS(id) ON DELETE CASCADE,
    b UUID REFERENCES USERS(id) ON DELETE CASCADE,
    CONSTRAINT unique_friendship UNIQUE (a, b),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE POSTS (
    id UUID PRIMARY KEY,
    content VARCHAR,
    creator UUID REFERENCES USERS(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TAGS (
    id SERIAL PRIMARY KEY,
    tag VARCHAR,
    post_id UUID REFERENCES POSTS(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE COMMENTS (
    id SERIAL PRIMARY KEY,
    post_id UUID REFERENCES POSTS(id) ON DELETE CASCADE,
    comment VARCHAR,
    user_id UUID REFERENCES USERS(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMIT TRANSACTION;