BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS USERS (
    id UUID PRIMARY KEY,
    email VARCHAR UNIQUE,
    name VARCHAR,
    image_url VARCHAR,
    password VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES USERS(id) ON DELETE CASCADE,
    bank_name VARCHAR NOT NULL,
    bank_account_number VARCHAR NOT NULL,
    balance INT,
    currency VARCHAR DEFAULT 'USD',
    transfer_proof_img VARCHAR,
    created_at BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())
);

COMMIT TRANSACTION;