version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  golang:
    image: golang
    ports:
      - "8000:8000"
    volumes:
      - ./:/go/src/app
    working_dir: /go/src/app
    command: go run main.go

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root