{
 "title": "BankxTrial",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_histogram_count[$__rate_interval])) by (path, method, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,  (rate(http_request_histogram_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_histogram_bucket{status=\"500\"}[$__rate_interval])) by (path, method, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GoRoutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(go_goroutines{instance=\"host.docker.internal:8080\", job=\"local-metrics\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}